### ISSUE TITLE
How to call multiple files same time?

### ISSUE THREAD

**Issue by rthannee** [dfcreative/save-file#18]
When I am trying to call save() multiple times, multiple download location dialogs are opening.
Can we control it? Please help me

**Comment by dy** [comment]
Hm. Have you seen examples of downloading multiple files? Not sure that's possible, usually services create signle zip archive.
You can define methods in async fashion, then the dialogs will download one after the other:
```js
await save('file1.png', data1)
await save('file2.png', data2)
await save('file3.png', data3)
```

**Comment by juhamust** [comment]
FYI: While this approach works, at least the Google Chrome requires the user to move the focus out of the tab and back in order to load the next file.

**Comment by dy** [comment]
Back in 2018 when that module was created, save file dialog would blur main page, therefore waiting for the next _window focus_ event made sense. If you have a better idea for how to organize async in browser - I can implement that (PR is also welcome).

**Comment by juhamust** [comment]
Thanks for sharing the functionality and reasoning behind it. In my case, I was able to solve it by combining the data (text and image) into one file using JSON and base64 encoding.
