### ISSUE TITLE
save with callback not working to response

### ISSUE THREAD

**Issue by bombkiml** [dfcreative/save-file#23]
i using with version 1.3.0

[My simple code]
```
const save = require('save-file')
save(myImage, saveTo, (err, rawData) => {
    if(err) { 
      console.log('save failed.')
    } else {
      console.log('saved.')
    }
});
```
[Run result]
```
nothing response on screen
``` 

But image saved to my path is work!

remark**
more than version 1.3.0  callback is working but save file not working

pls. help me

**Comment by dy** [comment]
There's no callback support from version 2. Use promise or await for that purpose:
```js
save(myImage, saveTo).then(data => {}, error => {})
```

**Comment by bombkiml** [comment]
thank you so much, i got it
